# Generated by Django 5.0.3 on 2024-03-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke_bot', '0002_joke_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joke',
            options={'verbose_name': 'Шутка', 'verbose_name_plural': 'Шутки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Юзер в чате', 'verbose_name_plural': 'Юзеры в чате'},
        ),
        migrations.AddField(
            model_name='user',
            name='absent',
            field=models.BooleanField(default=False),
        ),
    ]
